# Generated by Django 4.1.7 on 2023-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
